# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignerFiles/mainwindow_test_subwells_2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1600, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 1000))
        MainWindow.setBaseSize(QtCore.QSize(1600, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.verticalFrame.setAutoFillBackground(True)
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.verticalFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 671, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PrepDate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PrepDate.setObjectName("PrepDate")
        self.gridLayout_3.addWidget(self.PrepDate, 2, 1, 1, 1)
        self.ProjectCode = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ProjectCode.setObjectName("ProjectCode")
        self.gridLayout_3.addWidget(self.ProjectCode, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.ImageDate = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ImageDate.setObjectName("ImageDate")
        self.gridLayout_3.addWidget(self.ImageDate, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        self.TargetName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.TargetName.setObjectName("TargetName")
        self.gridLayout_3.addWidget(self.TargetName, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 2, 1, 1)
        self.PlateName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PlateName.setObjectName("PlateName")
        self.gridLayout_3.addWidget(self.PlateName, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 2, 1, 1)
        self.label_NDays = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_NDays.setObjectName("label_NDays")
        self.gridLayout_3.addWidget(self.label_NDays, 3, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.scrollAreaPlate = QtWidgets.QScrollArea(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaPlate.sizePolicy().hasHeightForWidth())
        self.scrollAreaPlate.setSizePolicy(sizePolicy)
        self.scrollAreaPlate.setMouseTracking(True)
        self.scrollAreaPlate.setLineWidth(5)
        self.scrollAreaPlate.setMidLineWidth(0)
        self.scrollAreaPlate.setWidgetResizable(True)
        self.scrollAreaPlate.setObjectName("scrollAreaPlate")
        self.scrollAreaPlateContent = QtWidgets.QWidget()
        self.scrollAreaPlateContent.setGeometry(QtCore.QRect(0, 0, 646, 373))
        self.scrollAreaPlateContent.setObjectName("scrollAreaPlateContent")
        self.scrollAreaPlate.setWidget(self.scrollAreaPlateContent)
        self.gridLayout.addWidget(self.scrollAreaPlate, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 50, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ProjectDetails = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ProjectDetails.sizePolicy().hasHeightForWidth())
        self.label_ProjectDetails.setSizePolicy(sizePolicy)
        self.label_ProjectDetails.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_ProjectDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ProjectDetails.setObjectName("label_ProjectDetails")
        self.horizontalLayout_4.addWidget(self.label_ProjectDetails, 0, QtCore.Qt.AlignLeft)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar, 0, QtCore.Qt.AlignLeft)
        self.label_LastSaved = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LastSaved.sizePolicy().hasHeightForWidth())
        self.label_LastSaved.setSizePolicy(sizePolicy)
        self.label_LastSaved.setMinimumSize(QtCore.QSize(220, 0))
        self.label_LastSaved.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_LastSaved.setText("")
        self.label_LastSaved.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LastSaved.setObjectName("label_LastSaved")
        self.horizontalLayout_4.addWidget(self.label_LastSaved)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.FilterBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.FilterBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterBox.sizePolicy().hasHeightForWidth())
        self.FilterBox.setSizePolicy(sizePolicy)
        self.FilterBox.setMinimumSize(QtCore.QSize(635, 130))
        self.FilterBox.setMaximumSize(QtCore.QSize(650, 170))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.FilterBox.setFont(font)
        self.FilterBox.setAutoFillBackground(False)
        self.FilterBox.setFlat(False)
        self.FilterBox.setCheckable(False)
        self.FilterBox.setObjectName("FilterBox")
        self.layoutWidget = QtWidgets.QWidget(self.FilterBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 32, 631, 94))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_All = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_All.setChecked(True)
        self.radioButton_All.setObjectName("radioButton_All")
        self.verticalLayout.addWidget(self.radioButton_All)
        self.radioButton_Crystal = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Crystal.setObjectName("radioButton_Crystal")
        self.verticalLayout.addWidget(self.radioButton_Crystal)
        self.radioButton_Subwella = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Subwella.setObjectName("radioButton_Subwella")
        self.verticalLayout.addWidget(self.radioButton_Subwella)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_Clear = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Clear.setObjectName("radioButton_Clear")
        self.verticalLayout_2.addWidget(self.radioButton_Clear)
        self.radioButton_Other = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Other.setObjectName("radioButton_Other")
        self.verticalLayout_2.addWidget(self.radioButton_Other)
        self.radioButton_Subwellb = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Subwellb.setObjectName("radioButton_Subwellb")
        self.verticalLayout_2.addWidget(self.radioButton_Subwellb)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_Precipitate = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Precipitate.setObjectName("radioButton_Precipitate")
        self.verticalLayout_3.addWidget(self.radioButton_Precipitate)
        self.radioButton_PhaseSep = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_PhaseSep.setObjectName("radioButton_PhaseSep")
        self.verticalLayout_3.addWidget(self.radioButton_PhaseSep)
        self.radioButton_Subwellc = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Subwellc.setObjectName("radioButton_Subwellc")
        self.verticalLayout_3.addWidget(self.radioButton_Subwellc)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_Unsorted = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_Unsorted.setObjectName("radioButton_Unsorted")
        self.verticalLayout_4.addWidget(self.radioButton_Unsorted)
        self.radioButton_HasNotes = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_HasNotes.setObjectName("radioButton_HasNotes")
        self.verticalLayout_4.addWidget(self.radioButton_HasNotes)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.labelVisuClassif = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVisuClassif.sizePolicy().hasHeightForWidth())
        self.labelVisuClassif.setSizePolicy(sizePolicy)
        self.labelVisuClassif.setMinimumSize(QtCore.QSize(143, 50))
        self.labelVisuClassif.setMaximumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelVisuClassif.setFont(font)
        self.labelVisuClassif.setFrameShape(QtWidgets.QFrame.Box)
        self.labelVisuClassif.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelVisuClassif.setText("")
        self.labelVisuClassif.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisuClassif.setObjectName("labelVisuClassif")
        self.horizontalLayout_2.addWidget(self.labelVisuClassif, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.FilterBox, 2, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.verticalFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 650, 1541, 280))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_Timeline = QtWidgets.QScrollArea(self.gridLayoutWidget_2)
        self.scrollArea_Timeline.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_Timeline.sizePolicy().hasHeightForWidth())
        self.scrollArea_Timeline.setSizePolicy(sizePolicy)
        self.scrollArea_Timeline.setMinimumSize(QtCore.QSize(830, 250))
        self.scrollArea_Timeline.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_Timeline.setBaseSize(QtCore.QSize(400, 250))
        self.scrollArea_Timeline.setWidgetResizable(True)
        self.scrollArea_Timeline.setObjectName("scrollArea_Timeline")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 826, 246))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_Timeline.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea_Timeline, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(38, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Notes_TextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.Notes_TextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Notes_TextEdit.sizePolicy().hasHeightForWidth())
        self.Notes_TextEdit.setSizePolicy(sizePolicy)
        self.Notes_TextEdit.setMinimumSize(QtCore.QSize(300, 250))
        self.Notes_TextEdit.setMaximumSize(QtCore.QSize(16777215, 300))
        self.Notes_TextEdit.setBaseSize(QtCore.QSize(100, 0))
        self.Notes_TextEdit.setWhatsThis("")
        self.Notes_TextEdit.setAccessibleDescription("")
        self.Notes_TextEdit.setAutoFillBackground(False)
        self.Notes_TextEdit.setObjectName("Notes_TextEdit")
        self.gridLayout_2.addWidget(self.Notes_TextEdit, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Timeline = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_Timeline.setMinimumSize(QtCore.QSize(121, 20))
        self.label_Timeline.setMaximumSize(QtCore.QSize(140, 20))
        self.label_Timeline.setObjectName("label_Timeline")
        self.horizontalLayout_3.addWidget(self.label_Timeline)
        self.label_CurrentWell = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_CurrentWell.setObjectName("label_CurrentWell")
        self.horizontalLayout_3.addWidget(self.label_CurrentWell)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(148, 135))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setBaseSize(QtCore.QSize(150, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 133, 99))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_DisplayHeatMap = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_DisplayHeatMap.setObjectName("pushButton_DisplayHeatMap")
        self.verticalLayout_5.addWidget(self.pushButton_DisplayHeatMap)
        self.pushButton_ExportToPDF = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_ExportToPDF.setObjectName("pushButton_ExportToPDF")
        self.verticalLayout_5.addWidget(self.pushButton_ExportToPDF)
        self.gridLayout_2.addWidget(self.groupBox, 0, 3, 2, 1, QtCore.Qt.AlignBottom)
        self.Scoring_Layout = QtWidgets.QGridLayout()
        self.Scoring_Layout.setObjectName("Scoring_Layout")
        self.radioButton_ScoreCrystal = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ScoreCrystal.setFont(font)
        self.radioButton_ScoreCrystal.setObjectName("radioButton_ScoreCrystal")
        self.Scoring_Layout.addWidget(self.radioButton_ScoreCrystal, 2, 0, 1, 1)
        self.radioButton_ScoreClear = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ScoreClear.setFont(font)
        self.radioButton_ScoreClear.setAutoFillBackground(False)
        self.radioButton_ScoreClear.setObjectName("radioButton_ScoreClear")
        self.Scoring_Layout.addWidget(self.radioButton_ScoreClear, 0, 0, 1, 1)
        self.radioButton_ScorePhaseSep = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ScorePhaseSep.setFont(font)
        self.radioButton_ScorePhaseSep.setObjectName("radioButton_ScorePhaseSep")
        self.Scoring_Layout.addWidget(self.radioButton_ScorePhaseSep, 3, 0, 1, 1)
        self.radioButton_ScorePrecipitate = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ScorePrecipitate.setFont(font)
        self.radioButton_ScorePrecipitate.setObjectName("radioButton_ScorePrecipitate")
        self.Scoring_Layout.addWidget(self.radioButton_ScorePrecipitate, 1, 0, 1, 1)
        self.radioButton_ScoreOther = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ScoreOther.setFont(font)
        self.radioButton_ScoreOther.setObjectName("radioButton_ScoreOther")
        self.Scoring_Layout.addWidget(self.radioButton_ScoreOther, 4, 0, 1, 1)
        self.label_ShortcutClear = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.label_ShortcutClear.setFont(font)
        self.label_ShortcutClear.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShortcutClear.setObjectName("label_ShortcutClear")
        self.Scoring_Layout.addWidget(self.label_ShortcutClear, 0, 1, 1, 1)
        self.label_ShortcutPrec = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.label_ShortcutPrec.setFont(font)
        self.label_ShortcutPrec.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShortcutPrec.setObjectName("label_ShortcutPrec")
        self.Scoring_Layout.addWidget(self.label_ShortcutPrec, 1, 1, 1, 1)
        self.label_ShortcutCrystal = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.label_ShortcutCrystal.setFont(font)
        self.label_ShortcutCrystal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShortcutCrystal.setObjectName("label_ShortcutCrystal")
        self.Scoring_Layout.addWidget(self.label_ShortcutCrystal, 2, 1, 1, 1)
        self.label_ShortcutPhaseSep = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.label_ShortcutPhaseSep.setFont(font)
        self.label_ShortcutPhaseSep.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShortcutPhaseSep.setObjectName("label_ShortcutPhaseSep")
        self.Scoring_Layout.addWidget(self.label_ShortcutPhaseSep, 3, 1, 1, 1)
        self.label_ShortcutOther = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.label_ShortcutOther.setFont(font)
        self.label_ShortcutOther.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ShortcutOther.setObjectName("label_ShortcutOther")
        self.Scoring_Layout.addWidget(self.label_ShortcutOther, 4, 1, 1, 1)
        self.radioButton_ScoreUnknown = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_ScoreUnknown.setObjectName("radioButton_ScoreUnknown")
        self.Scoring_Layout.addWidget(self.radioButton_ScoreUnknown, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.Scoring_Layout, 1, 1, 1, 1)
        self.ImageViewer = QtWidgets.QScrollArea(self.verticalFrame)
        self.ImageViewer.setGeometry(QtCore.QRect(700, 10, 861, 631))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        self.ImageViewer.setFont(font)
        self.ImageViewer.setWidgetResizable(True)
        self.ImageViewer.setObjectName("ImageViewer")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 857, 627))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.ImageViewer.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.addWidget(self.verticalFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuDisplay_Heat_Map = QtWidgets.QMenu(self.menuBar)
        self.menuDisplay_Heat_Map.setObjectName("menuDisplay_Heat_Map")
        self.menuShow_autoMARCO_Grid = QtWidgets.QMenu(self.menuDisplay_Heat_Map)
        self.menuShow_autoMARCO_Grid.setObjectName("menuShow_autoMARCO_Grid")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuScreen_Tables = QtWidgets.QMenu(self.menuBar)
        self.menuScreen_Tables.setObjectName("menuScreen_Tables")
        self.menuMolecular_Dimensions = QtWidgets.QMenu(self.menuScreen_Tables)
        self.menuMolecular_Dimensions.setObjectName("menuMolecular_Dimensions")
        self.menuNextal = QtWidgets.QMenu(self.menuScreen_Tables)
        self.menuNextal.setObjectName("menuNextal")
        self.menuJena_Bioscience = QtWidgets.QMenu(self.menuScreen_Tables)
        self.menuJena_Bioscience.setObjectName("menuJena_Bioscience")
        self.menuHampton_Research = QtWidgets.QMenu(self.menuScreen_Tables)
        self.menuHampton_Research.setObjectName("menuHampton_Research")
        self.menuPlate_Overview = QtWidgets.QMenu(self.menuBar)
        self.menuPlate_Overview.setObjectName("menuPlate_Overview")
        self.menuExport_to_PNG = QtWidgets.QMenu(self.menuPlate_Overview)
        self.menuExport_to_PNG.setObjectName("menuExport_to_PNG")
        MainWindow.setMenuBar(self.menuBar)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setStatusTip("")
        self.openFile.setObjectName("openFile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.openDir = QtWidgets.QAction(MainWindow)
        self.openDir.setObjectName("openDir")
        self.actionQuit_2 = QtWidgets.QAction(MainWindow)
        self.actionQuit_2.setObjectName("actionQuit_2")
        self.actionDisplay_Heat_Map = QtWidgets.QAction(MainWindow)
        self.actionDisplay_Heat_Map.setObjectName("actionDisplay_Heat_Map")
        self.actionExport_to_PDF = QtWidgets.QAction(MainWindow)
        self.actionExport_to_PDF.setObjectName("actionExport_to_PDF")
        self.actionCalculate_Statistics = QtWidgets.QAction(MainWindow)
        self.actionCalculate_Statistics.setObjectName("actionCalculate_Statistics")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAutomated_Annotation_MARCO = QtWidgets.QAction(MainWindow)
        self.actionAutomated_Annotation_MARCO.setObjectName("actionAutomated_Annotation_MARCO")
        self.actionautoMARCO_subwell_a = QtWidgets.QAction(MainWindow)
        self.actionautoMARCO_subwell_a.setObjectName("actionautoMARCO_subwell_a")
        self.actionautoMARCO_subwell_b = QtWidgets.QAction(MainWindow)
        self.actionautoMARCO_subwell_b.setObjectName("actionautoMARCO_subwell_b")
        self.actionautoMARCO_subwell_c = QtWidgets.QAction(MainWindow)
        self.actionautoMARCO_subwell_c.setObjectName("actionautoMARCO_subwell_c")
        self.actionautoMARCO_no_subwell = QtWidgets.QAction(MainWindow)
        self.actionautoMARCO_no_subwell.setObjectName("actionautoMARCO_no_subwell")
        self.actionAutoCrop = QtWidgets.QAction(MainWindow)
        self.actionAutoCrop.setObjectName("actionAutoCrop")
        self.actionAutoMerge = QtWidgets.QAction(MainWindow)
        self.actionAutoMerge.setObjectName("actionAutoMerge")
        self.actionMD_PGA = QtWidgets.QAction(MainWindow)
        self.actionMD_PGA.setObjectName("actionMD_PGA")
        self.actionNextal_MbClassII_Suite = QtWidgets.QAction(MainWindow)
        self.actionNextal_MbClassII_Suite.setObjectName("actionNextal_MbClassII_Suite")
        self.actionNextal_Classics_Suite = QtWidgets.QAction(MainWindow)
        self.actionNextal_Classics_Suite.setObjectName("actionNextal_Classics_Suite")
        self.actionNextal_ClassicsII_Suite = QtWidgets.QAction(MainWindow)
        self.actionNextal_ClassicsII_Suite.setObjectName("actionNextal_ClassicsII_Suite")
        self.actionNextal_PEGII_Suite = QtWidgets.QAction(MainWindow)
        self.actionNextal_PEGII_Suite.setObjectName("actionNextal_PEGII_Suite")
        self.actionNeXtal_Protein_Complex_Suite = QtWidgets.QAction(MainWindow)
        self.actionNeXtal_Protein_Complex_Suite.setObjectName("actionNeXtal_Protein_Complex_Suite")
        self.actionNeXtal_Nucleix_Suite = QtWidgets.QAction(MainWindow)
        self.actionNeXtal_Nucleix_Suite.setObjectName("actionNeXtal_Nucleix_Suite")
        self.actionJena_JCSG_Plus_Plus = QtWidgets.QAction(MainWindow)
        self.actionJena_JCSG_Plus_Plus.setObjectName("actionJena_JCSG_Plus_Plus")
        self.actionJCSG_Plus_Plus = QtWidgets.QAction(MainWindow)
        self.actionJCSG_Plus_Plus.setObjectName("actionJCSG_Plus_Plus")
        self.actionJBScreen_Classic_HTS_I = QtWidgets.QAction(MainWindow)
        self.actionJBScreen_Classic_HTS_I.setObjectName("actionJBScreen_Classic_HTS_I")
        self.actionJBScreen_Classic_HTS_II = QtWidgets.QAction(MainWindow)
        self.actionJBScreen_Classic_HTS_II.setObjectName("actionJBScreen_Classic_HTS_II")
        self.actionPi_PEG_HTS = QtWidgets.QAction(MainWindow)
        self.actionPi_PEG_HTS.setObjectName("actionPi_PEG_HTS")
        self.actionPeg_Rx1Rx2 = QtWidgets.QAction(MainWindow)
        self.actionPeg_Rx1Rx2.setObjectName("actionPeg_Rx1Rx2")
        self.actionSaltRx = QtWidgets.QAction(MainWindow)
        self.actionSaltRx.setObjectName("actionSaltRx")
        self.actionMD_PACT_Premier = QtWidgets.QAction(MainWindow)
        self.actionMD_PACT_Premier.setObjectName("actionMD_PACT_Premier")
        self.actionNextal_JCSG_Plus = QtWidgets.QAction(MainWindow)
        self.actionNextal_JCSG_Plus.setObjectName("actionNextal_JCSG_Plus")
        self.actionJBScreen_Classic_1_4 = QtWidgets.QAction(MainWindow)
        self.actionJBScreen_Classic_1_4.setObjectName("actionJBScreen_Classic_1_4")
        self.actionJBScreen_Classic_5_8 = QtWidgets.QAction(MainWindow)
        self.actionJBScreen_Classic_5_8.setObjectName("actionJBScreen_Classic_5_8")
        self.actionMD_MIDAS = QtWidgets.QAction(MainWindow)
        self.actionMD_MIDAS.setObjectName("actionMD_MIDAS")
        self.actionMD_BCS_Screen = QtWidgets.QAction(MainWindow)
        self.actionMD_BCS_Screen.setObjectName("actionMD_BCS_Screen")
        self.actionDelete_Folder_rawimages = QtWidgets.QAction(MainWindow)
        self.actionDelete_Folder_rawimages.setObjectName("actionDelete_Folder_rawimages")
        self.actionDelete_Folder_cropped = QtWidgets.QAction(MainWindow)
        self.actionDelete_Folder_cropped.setObjectName("actionDelete_Folder_cropped")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionNeXtal_Ammonium_Sulfate_Suite = QtWidgets.QAction(MainWindow)
        self.actionNeXtal_Ammonium_Sulfate_Suite.setObjectName("actionNeXtal_Ammonium_Sulfate_Suite")
        self.action_Cryo_HT = QtWidgets.QAction(MainWindow)
        self.action_Cryo_HT.setObjectName("action_Cryo_HT")
        self.actionimport_RockMaker_XML = QtWidgets.QAction(MainWindow)
        self.actionimport_RockMaker_XML.setObjectName("actionimport_RockMaker_XML")
        self.action_Additive_screen_HT = QtWidgets.QAction(MainWindow)
        self.action_Additive_screen_HT.setObjectName("action_Additive_screen_HT")
        self.actionPlateSubwell_a = QtWidgets.QAction(MainWindow)
        self.actionPlateSubwell_a.setObjectName("actionPlateSubwell_a")
        self.actionPlateSubwell_b = QtWidgets.QAction(MainWindow)
        self.actionPlateSubwell_b.setObjectName("actionPlateSubwell_b")
        self.actionPlateSubwell_c = QtWidgets.QAction(MainWindow)
        self.actionPlateSubwell_c.setObjectName("actionPlateSubwell_c")
        self.actionPlateno_subwell = QtWidgets.QAction(MainWindow)
        self.actionPlateno_subwell.setObjectName("actionPlateno_subwell")
        self.PlateScreenshot_subwell_a = QtWidgets.QAction(MainWindow)
        self.PlateScreenshot_subwell_a.setObjectName("PlateScreenshot_subwell_a")
        self.PlateScreenshot_subwell_b = QtWidgets.QAction(MainWindow)
        self.PlateScreenshot_subwell_b.setObjectName("PlateScreenshot_subwell_b")
        self.PlateScreenshot_subwell_c = QtWidgets.QAction(MainWindow)
        self.PlateScreenshot_subwell_c.setObjectName("PlateScreenshot_subwell_c")
        self.PlateScreenshot_no_subwell = QtWidgets.QAction(MainWindow)
        self.PlateScreenshot_no_subwell.setObjectName("PlateScreenshot_no_subwell")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.openDir)
        self.menuFile.addAction(self.actionExport_to_PDF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_Folder_cropped)
        self.menuFile.addAction(self.actionDelete_Folder_rawimages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuShow_autoMARCO_Grid.addAction(self.actionautoMARCO_subwell_a)
        self.menuShow_autoMARCO_Grid.addAction(self.actionautoMARCO_subwell_b)
        self.menuShow_autoMARCO_Grid.addAction(self.actionautoMARCO_subwell_c)
        self.menuShow_autoMARCO_Grid.addAction(self.actionautoMARCO_no_subwell)
        self.menuDisplay_Heat_Map.addAction(self.actionAutoCrop)
        self.menuDisplay_Heat_Map.addAction(self.actionAutoMerge)
        self.menuDisplay_Heat_Map.addAction(self.actionAutomated_Annotation_MARCO)
        self.menuDisplay_Heat_Map.addAction(self.actionCalculate_Statistics)
        self.menuDisplay_Heat_Map.addAction(self.actionDisplay_Heat_Map)
        self.menuDisplay_Heat_Map.addAction(self.menuShow_autoMARCO_Grid.menuAction())
        self.menuHelp.addAction(self.actionShortcuts)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionManual)
        self.menuMolecular_Dimensions.addAction(self.actionMD_BCS_Screen)
        self.menuMolecular_Dimensions.addAction(self.actionMD_MIDAS)
        self.menuMolecular_Dimensions.addAction(self.actionMD_PACT_Premier)
        self.menuMolecular_Dimensions.addAction(self.actionMD_PGA)
        self.menuNextal.addAction(self.actionNeXtal_Ammonium_Sulfate_Suite)
        self.menuNextal.addAction(self.actionNextal_Classics_Suite)
        self.menuNextal.addAction(self.actionNextal_ClassicsII_Suite)
        self.menuNextal.addAction(self.actionNextal_JCSG_Plus)
        self.menuNextal.addAction(self.actionNextal_MbClassII_Suite)
        self.menuNextal.addAction(self.actionNeXtal_Nucleix_Suite)
        self.menuNextal.addAction(self.actionNextal_PEGII_Suite)
        self.menuNextal.addAction(self.actionNeXtal_Protein_Complex_Suite)
        self.menuJena_Bioscience.addAction(self.actionJBScreen_Classic_1_4)
        self.menuJena_Bioscience.addAction(self.actionJBScreen_Classic_5_8)
        self.menuJena_Bioscience.addAction(self.actionJBScreen_Classic_HTS_I)
        self.menuJena_Bioscience.addAction(self.actionJBScreen_Classic_HTS_II)
        self.menuJena_Bioscience.addAction(self.actionJena_JCSG_Plus_Plus)
        self.menuJena_Bioscience.addAction(self.actionPi_PEG_HTS)
        self.menuHampton_Research.addAction(self.action_Additive_screen_HT)
        self.menuHampton_Research.addAction(self.action_Cryo_HT)
        self.menuHampton_Research.addAction(self.actionPeg_Rx1Rx2)
        self.menuHampton_Research.addAction(self.actionSaltRx)
        self.menuScreen_Tables.addSeparator()
        self.menuScreen_Tables.addAction(self.menuHampton_Research.menuAction())
        self.menuScreen_Tables.addAction(self.menuJena_Bioscience.menuAction())
        self.menuScreen_Tables.addAction(self.menuMolecular_Dimensions.menuAction())
        self.menuScreen_Tables.addAction(self.menuNextal.menuAction())
        self.menuScreen_Tables.addSeparator()
        self.menuScreen_Tables.addAction(self.actionimport_RockMaker_XML)
        self.menuExport_to_PNG.addAction(self.PlateScreenshot_subwell_a)
        self.menuExport_to_PNG.addAction(self.PlateScreenshot_subwell_b)
        self.menuExport_to_PNG.addAction(self.PlateScreenshot_subwell_c)
        self.menuExport_to_PNG.addAction(self.PlateScreenshot_no_subwell)
        self.menuPlate_Overview.addAction(self.actionPlateSubwell_a)
        self.menuPlate_Overview.addAction(self.actionPlateSubwell_b)
        self.menuPlate_Overview.addAction(self.actionPlateSubwell_c)
        self.menuPlate_Overview.addAction(self.actionPlateno_subwell)
        self.menuPlate_Overview.addSeparator()
        self.menuPlate_Overview.addAction(self.menuExport_to_PNG.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuDisplay_Heat_Map.menuAction())
        self.menuBar.addAction(self.menuScreen_Tables.menuAction())
        self.menuBar.addAction(self.menuPlate_Overview.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AMi Image Analysis for LCPB AMi version x.x.x"))
        self.PrepDate.setText(_translate("MainWindow", "----"))
        self.ProjectCode.setText(_translate("MainWindow", "----"))
        self.label_8.setText(_translate("MainWindow", "Project Code: "))
        self.label_6.setText(_translate("MainWindow", "Image date: "))
        self.ImageDate.setText(_translate("MainWindow", "----"))
        self.label_10.setText(_translate("MainWindow", "Prep date: "))
        self.label_7.setText(_translate("MainWindow", "Target name: "))
        self.TargetName.setText(_translate("MainWindow", "----"))
        self.label_9.setText(_translate("MainWindow", "Plate name: "))
        self.PlateName.setText(_translate("MainWindow", "----"))
        self.label.setText(_translate("MainWindow", "Days since setup:"))
        self.label_NDays.setText(_translate("MainWindow", "----"))
        self.label_ProjectDetails.setText(_translate("MainWindow", "Project Details"))
        self.FilterBox.setTitle(_translate("MainWindow", "Filter"))
        self.radioButton_All.setText(_translate("MainWindow", "All"))
        self.radioButton_Crystal.setText(_translate("MainWindow", "Crystal"))
        self.radioButton_Subwella.setText(_translate("MainWindow", "Subwell a"))
        self.radioButton_Clear.setText(_translate("MainWindow", "Clear"))
        self.radioButton_Other.setText(_translate("MainWindow", "Other"))
        self.radioButton_Subwellb.setText(_translate("MainWindow", "Subwell b"))
        self.radioButton_Precipitate.setText(_translate("MainWindow", "Precipitate"))
        self.radioButton_PhaseSep.setText(_translate("MainWindow", "Phase Separation"))
        self.radioButton_Subwellc.setText(_translate("MainWindow", "Subwell c"))
        self.radioButton_Unsorted.setText(_translate("MainWindow", "Unsorted"))
        self.radioButton_HasNotes.setText(_translate("MainWindow", "With Notes"))
        self.label_2.setText(_translate("MainWindow", "Notes"))
        self.label_4.setText(_translate("MainWindow", "Drop Score"))
        self.label_Timeline.setText(_translate("MainWindow", "Timeline for well :"))
        self.label_CurrentWell.setText(_translate("MainWindow", "------"))
        self.pushButton_DisplayHeatMap.setText(_translate("MainWindow", "Display Heat Map"))
        self.pushButton_ExportToPDF.setText(_translate("MainWindow", "Create Report\n"
"for Well"))
        self.radioButton_ScoreCrystal.setText(_translate("MainWindow", "Crystal"))
        self.radioButton_ScoreClear.setText(_translate("MainWindow", "Clear"))
        self.radioButton_ScorePhaseSep.setText(_translate("MainWindow", "Phase Separation"))
        self.radioButton_ScorePrecipitate.setText(_translate("MainWindow", "Precipitate"))
        self.radioButton_ScoreOther.setText(_translate("MainWindow", "Other"))
        self.label_ShortcutClear.setText(_translate("MainWindow", "(-)"))
        self.label_ShortcutPrec.setText(_translate("MainWindow", "(-)"))
        self.label_ShortcutCrystal.setText(_translate("MainWindow", "(-)"))
        self.label_ShortcutPhaseSep.setText(_translate("MainWindow", "(-)"))
        self.label_ShortcutOther.setText(_translate("MainWindow", "(-)"))
        self.radioButton_ScoreUnknown.setText(_translate("MainWindow", "Unknown"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDisplay_Heat_Map.setTitle(_translate("MainWindow", "Tools"))
        self.menuShow_autoMARCO_Grid.setTitle(_translate("MainWindow", "Show autoMARCO Results"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuScreen_Tables.setTitle(_translate("MainWindow", "Screen Tables"))
        self.menuMolecular_Dimensions.setTitle(_translate("MainWindow", "Molecular Dimensions"))
        self.menuNextal.setTitle(_translate("MainWindow", "Nextal"))
        self.menuJena_Bioscience.setTitle(_translate("MainWindow", "Jena Bioscience"))
        self.menuHampton_Research.setTitle(_translate("MainWindow", "Hampton Research"))
        self.menuPlate_Overview.setTitle(_translate("MainWindow", "Plate Overview"))
        self.menuExport_to_PNG.setTitle(_translate("MainWindow", "Export Plate to JPG"))
        self.openFile.setText(_translate("MainWindow", "Open File"))
        self.openFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.openDir.setText(_translate("MainWindow", "Open Directory"))
        self.openDir.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit"))
        self.actionQuit_2.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionDisplay_Heat_Map.setText(_translate("MainWindow", "Display Heat Map"))
        self.actionDisplay_Heat_Map.setShortcut(_translate("MainWindow", "Shift+H"))
        self.actionExport_to_PDF.setText(_translate("MainWindow", "Create Report for Well"))
        self.actionExport_to_PDF.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionCalculate_Statistics.setText(_translate("MainWindow", "Calculate Statistics"))
        self.actionCalculate_Statistics.setShortcut(_translate("MainWindow", "Shift+S"))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAutomated_Annotation_MARCO.setText(_translate("MainWindow", "Automated Annotation (MARCO)"))
        self.actionautoMARCO_subwell_a.setText(_translate("MainWindow", "autoMARCO subwell a"))
        self.actionautoMARCO_subwell_b.setText(_translate("MainWindow", "autoMARCO subwell b"))
        self.actionautoMARCO_subwell_c.setText(_translate("MainWindow", "autoMARCO subwell c"))
        self.actionautoMARCO_no_subwell.setText(_translate("MainWindow", "autoMARCO no subwell"))
        self.actionAutoCrop.setText(_translate("MainWindow", "AutoCrop"))
        self.actionAutoCrop.setShortcut(_translate("MainWindow", "Shift+C"))
        self.actionAutoMerge.setText(_translate("MainWindow", "AutoMerge"))
        self.actionAutoMerge.setShortcut(_translate("MainWindow", "Shift+M"))
        self.actionMD_PGA.setText(_translate("MainWindow", "MD PGA"))
        self.actionNextal_MbClassII_Suite.setText(_translate("MainWindow", "Nextal MbClassII Suite"))
        self.actionNextal_Classics_Suite.setText(_translate("MainWindow", "Nextal Classics Suite"))
        self.actionNextal_ClassicsII_Suite.setText(_translate("MainWindow", "Nextal ClassicsII Suite"))
        self.actionNextal_PEGII_Suite.setText(_translate("MainWindow", "Nextal PEGII Suite"))
        self.actionNeXtal_Protein_Complex_Suite.setText(_translate("MainWindow", "NeXtal Protein-Complex Suite"))
        self.actionNeXtal_Nucleix_Suite.setText(_translate("MainWindow", "NeXtal Nucleix Suite"))
        self.actionJena_JCSG_Plus_Plus.setText(_translate("MainWindow", "JCSG Plus Plus"))
        self.actionJCSG_Plus_Plus.setText(_translate("MainWindow", "JCSG Plus Plus"))
        self.actionJBScreen_Classic_HTS_I.setText(_translate("MainWindow", "JBScreen Classic HTS I"))
        self.actionJBScreen_Classic_HTS_II.setText(_translate("MainWindow", "JBScreen Classic HTS II"))
        self.actionPi_PEG_HTS.setText(_translate("MainWindow", "Pi-PEG HTS"))
        self.actionPeg_Rx1Rx2.setText(_translate("MainWindow", "Peg Rx1Rx2"))
        self.actionSaltRx.setText(_translate("MainWindow", "SaltRx"))
        self.actionMD_PACT_Premier.setText(_translate("MainWindow", "MD PACT Premier"))
        self.actionNextal_JCSG_Plus.setText(_translate("MainWindow", "Nextal JCSG Plus"))
        self.actionJBScreen_Classic_1_4.setText(_translate("MainWindow", "JBScreen Classic 1-4"))
        self.actionJBScreen_Classic_5_8.setText(_translate("MainWindow", "JBScreen Classic 5-8"))
        self.actionMD_MIDAS.setText(_translate("MainWindow", "MD MIDAS"))
        self.actionMD_BCS_Screen.setText(_translate("MainWindow", "MD BCS Screen"))
        self.actionDelete_Folder_rawimages.setText(_translate("MainWindow", "Delete \"rawimages\""))
        self.actionDelete_Folder_cropped.setText(_translate("MainWindow", "Delete \"cropped\""))
        self.actionDelete_Folder_cropped.setToolTip(_translate("MainWindow", "Delete \"cropped\""))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionNeXtal_Ammonium_Sulfate_Suite.setText(_translate("MainWindow", "NeXtal Ammonium Sulfate Suite"))
        self.action_Cryo_HT.setText(_translate("MainWindow", "Cryo HT"))
        self.actionimport_RockMaker_XML.setText(_translate("MainWindow", "import RockMaker/Dragonfly XML"))
        self.action_Additive_screen_HT.setText(_translate("MainWindow", "Additive screen HT"))
        self.actionPlateSubwell_a.setText(_translate("MainWindow", "subwell a (Show/Refresh)"))
        self.actionPlateSubwell_a.setShortcut(_translate("MainWindow", "Shift+A"))
        self.actionPlateSubwell_b.setText(_translate("MainWindow", "subwell b (Show/Refresh)"))
        self.actionPlateSubwell_b.setShortcut(_translate("MainWindow", "Shift+B"))
        self.actionPlateSubwell_c.setText(_translate("MainWindow", "subwell c (Show/Refresh)"))
        self.actionPlateSubwell_c.setShortcut(_translate("MainWindow", "Shift+C"))
        self.actionPlateno_subwell.setText(_translate("MainWindow", "no subwell (Show/Refresh)"))
        self.actionPlateno_subwell.setShortcut(_translate("MainWindow", "Shift+D"))
        self.PlateScreenshot_subwell_a.setText(_translate("MainWindow", "subwell a"))
        self.PlateScreenshot_subwell_b.setText(_translate("MainWindow", "subwell b"))
        self.PlateScreenshot_subwell_c.setText(_translate("MainWindow", "subwell c"))
        self.PlateScreenshot_no_subwell.setText(_translate("MainWindow", "no subwell"))


